FROM golang:1.25-bookworm AS build

WORKDIR /app

COPY go.mod go.sum ./
RUN go mod download

COPY . .

RUN CGO_ENABLED=0 GOOS=linux go build -o /out/api ./cmd/api


FROM alpine:3.20 AS runtime

WORKDIR /app

COPY --from=build /out/api /usr/local/bin/api
COPY --from=build /app/migrations ./migrations

EXPOSE 8080

ENTRYPOINT ["/usr/local/bin/api"]
